### ISSUE TITLE
BCR-08 Backup

### ISSUE THREAD

**Issue by mcsnps** [cloudsecurityalliance/continuous-audit-metrics#24]
[BCR-08] Backup
CSPs have native tools to configure backups for data storage. Audit tools such as Azure Policy must be used to detect if backup of storage, databases are enabled to generate metrics.

**Comment by apannetrat** [comment]
We need to translate this into a metric:
- What is measured? In what unit?
- What is a good objective to achieve?

**Comment by mcsnps** [comment]
Alain & Team,
First of all, my apologies for not being able to actively participate in the meetings that way thought.


  *   What is measured? In what unit?
     *   We can measure at least the data storage, VMs have backup features enabled, if these are geo-redundant. In Azure, Azure policy may be enabled to audit for all VMs, managed disks, storage accounts, databases, file shares. Then resource graph queries can be made to pull that compliance data to report metrics.
     *   Metrics may be
        *   % of VMs/SAs/DBs have backup enabled
        *   % of Geo-redundant backups
        *   This goes with data classification/labeling/tagging; % of storage with sensitive data does not have back up enabled.
        *
  *   What is a good objective to achieve?
     *   A good reference may be What is Azure Backup? - Azure Backup | Microsoft Docs<https://docs.microsoft.com/en-us/azure/backup/backup-overview>
     *   Objective may be to understand if all business-critical sensitive data storage have back up enabled, so that in case of any loss of data or if data storage in not available due to attack such as ransomware, there are alternative ways to recover the data.
Hope these make sense.

Best,
Monika Chakraborty
Associate Principal Consultant
Synopsys, Inc.
Burlington, MA USA

**Comment by apannetrat** [comment]
Suggestions: we need to re-work / clarify the current metric BCR-06-M1
- Clarify what is a "BCR test" because it might be too broad.
- Correct sampling period (less than 365 days), consider automation.

Question: do we need to create a new metric for BCR-08?
Ideas:
- Number of critical assets that have backup enabled
- Number of critical assets that have a geo-redundant backup
- Number of critical assets that have a successful backup restoration

Pre-requisite: the organisation has defined "criticality" of its assets. (e.g. Critical => critical to business continuity  [ex: image, database table])

**Comment by mcsnps** [comment]
I think “BCR Test” should include backup restoration that will help calculating RTO/RPO from the time test is initiated. The successful restoration also will feed to ‘Number of critical assets that have a successful backup restoration’ for BCR-08.

**Comment by apannetrat** [comment]
@mcsnps please propose a metric text consistent with the latest comments made on this issue. 

See https://github.com/cloudsecurityalliance/continuous-audit-metrics#2-with-a-github-issue for some general guidelines for contributions.

**Comment by mcsnps** [comment]
Primary CCMv4 Control ID: BCR-08

Primary Control Description: Periodically backup data stored in the cloud. Ensure the confidentiality, integrity and availability of the backup, and verify data restoration from backup for resiliency.

Related CCMv4 Control IDs: BCR-02, BCR-06

Auditing Guidance:
1. Examine the policy for identifying data for which a backup is required.
2. Examine the requirements for the security of such backups.
3. Evaluate the effectiveness of the backup and restore.

Metric ID: BCR-08-M1
Brief Description of the Metric:
This metric reports the percentage of critical data storages in cloud that have backup feature enabled.
For example, if customer of CSP is using S3 buckets, these must have backup enabled as mentioned in https://docs.aws.amazon.com/aws-backup/latest/devguide/s3-backups.html. All cloud resources and services that have data storing capability must ensure that data is backed up in a secure storage with proper access control in place.

Purpose of the metric:
Periodically backup data stored in the cloud.
Organizations must have policies to identify data and related storages that need backup for the purpose of restoration, if needed. Once total number of systems requiring backup is determined, continuous monitoring of backup configuration of those storages must generate total number of storages that have backup disabled. This metric then calculates percentage of systems that may fail system or data restoration.
By implementing this metric, SRE teams will have visibility of systems that may fail to restore and may analyze the reason why back up is disabled for those systems and enable backup, if required.

Expression: Percentage: 100*A/B
                A= Number of critical data storages in cloud that have backup feature enabled
                B= Total Number of critical data storages in cloud

Rules:
Criteria for criticality of data storages must be defined and there must be a list of critical data storages in cloud identified.

Metric ID: BCR-08-M2

Metric Description:
This metric reports the percentage of critical data storages in cloud that were successfully restored following a documented restoration process.
By implementing this metric, SRE teams will have visibility of systems that have failed to restore and may analyze the reason why restoration is failed - if data is tampered, storage had unauthorized access, storage was not available due to CSP outage etc.

Purpose of the metric:
Ensure the confidentiality, integrity, and availability of the backup, and verify data restoration from backup for resiliency.

Expression: Percentage: 100*A/B
                A= Number of critical data storages in cloud that could be successfully restored
                B= Total Number of critical data storages in cloud

Rules:
A process for data restoration must be in place and periodically tested for all critical data storages in cloud. Number of data storages that could be successfully restored must be determined either manually or using automated process.
