### ISSUE TITLE
IPY-03 lists Related CCMv4 Control IDs "CEK, IVS-02, IPY-02, DSP-05"

### ISSUE THREAD

**Issue by pritikin** [cloudsecurityalliance/continuous-audit-metrics#28]
seems it should be a specific CEK rather than the full set.
Also IPY-02 should probably be IPY-03

**Comment by mosi-k-platt** [comment]
@pritikin The original thought was that all the CEK controls support the IPY-03 control.

**Comment by pritikin** [comment]
this is fixed; it isn't visible in the current html due to the permissions problem.
