### ISSUE TITLE
want a github action to automatically lint the yaml file

### ISSUE THREAD

**Issue by pritikin** [cloudsecurityalliance/continuous-audit-metrics#7]
4/8 meeting discussion

**Comment by adalo** [comment]
On linting via GitHub Actions: 

https://medium.com/@knoldus/linting-via-github-actions-26d3bf855e26
https://stackoverflow.com/questions/71334373/is-there-a-way-i-can-validate-yaml-files-on-github

**Comment by apannetrat** [comment]
This is done but see #8 for a caveat.
